include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    sort_pub_dependencies: false

analyzer:
  exclude:
    - lib/**/*.g.dart
    - "**/*.freezed.dart"