name: training
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  retrofit: ^2.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  logging: ^1.0.2
  flutter_riverpod: ^1.0.3
  flutter_state_notifier: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.3
  build_runner: ^2.1.7
  freezed: ^1.1.0
  retrofit_generator: ^2.1.0+1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/lake.jpeg
    - images/arashi.jpeg
    - images/arashi.jpg
    - images/youtube_img.png
    - images/house_layout.png
    - images/start_guide.png
    - images/camera.png

